name: Cargo Semver Checks

on:
  workflow_call:
    inputs:
      bump-version:
        type: string
        required: true
      overwrite-tag:
        type: boolean
  workflow_dispatch:
    inputs:
      bump-version:
        description: "Bump version: (e.g. -> 3.6.1)"
        type: string
      release_type:
        type: choice
        default: none
        options:
          - none
          - patch
          - minor
          - major
      overwrite-tag:
        type: boolean

jobs:
  check-if-lib:
    uses: ./.github/workflows/crate_type.yaml

  get-baseline:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install jql
        uses: taiki-e/install-action@v2
        with:
          tool: jql

      - name: Current versions
        id: get_baseline_sha
        run: |
          version=$(cargo metadata --format-version=1 --no-deps | jql '"packages"|>"version"<|[0]' --raw-string);
          echo $version;
          current_tag=v$version;
          echo $current_tag;
          previous_tag=$(current_tag=$(git describe --tags) && git tag --list --sort=refname | grep -B1 "^$current_tag$" | head -n1);
          echo $previous_tag;
          previous_sha=git rev-parse "$previous_tag"
          echo $previous_sha;
          echo "baseline=$previous_sha" >> "$GITHUB_OUTPUT";

      - name: print if skip cargo-semver-checks
        if: ${{ steps.get_baseline_sha.outputs.baseline == '' }}
        run: echo "semver-checks needs a baseline. The baseline is the latest commit(hash) of the previous tag"
    outputs:
      baseline: ${{ steps.get_baseline_sha.outputs.baseline }}

  cargo-semver-checks:
    needs: [check-if-lib, get-baseline]
    if: ${{ needs.check-if-lib.outputs.is_lib == 'true' && needs.get-baseline.outputs.baseline != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install cargo-bump
        if: ${{ inputs.bump-version || inputs.release_type != 'none' }}
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-bump

      - name: Run cargo bump
        if: ${{ inputs.bump-version || inputs.release_type != 'none' }}
        run: cargo bump ${{ inputs.bump-version || inputs.release_type }}

      - name: Install cargo-semver-checks
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-semver-checks

      - name: Run cargo-semver-checks
        if: ${{ inputs.overwrite-tag == 'false' }}
        run: cargo semver-checks --baseline-rev ${{ needs.get-baseline.outputs.baseline }};
